version: '3'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - webdata:/var/www/php
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=Dorian
      - DB_PASSWORD=JeSuisUnMotDeP@sse314159
      - DB_NAME=AnimeGirlFan
    networks:
      - animenet
    restart: on-failure

  db:
    image: mysql:5.7
    volumes:
      # sql scripts to execute at the start of the database
      - ./mysql/sql:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_INITDB: /docker-entrypoint-initdb.d/granting.sql
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: AnimeGirlFan
      MYSQL_USER: Dorian
      MYSQL_PASSWORD: JeSuisUnMotDeP@sse314159
    networks:
      - animenet
    restart: on-failure

volumes:
  webdata:
  dbdata:

networks:
  animenet:
    #driver: bridge
