name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: ./prepare-app.sh
    - name: start the application
      run: ./start-app.sh
    - name: Test MongoDB connection
      run: docker-compose exec web php /var/www/html/db_connection.php
